# configure file
define CONFIGURE
...
# OSX
mkdir -p $(LIBS_DIR)
wget -O $(LIBS_DIR)/json.hpp https://raw.githubusercontent.com/nlohmann/json/8d92ca8/single_include/nlohmann/json.hpp
...
endef
export CONFIGURE